export const Events =[
      {
        "id": "1",
        "title": "Hacker Hive Starts ",
        "height": 70,
        "StartDate": "2023-02-25",
        "EndDate": "2023-02-25",
        "StartTime": "11:00 AM",
        "EndTime": "09:00 PM",
        "desc": "Hacker Hive is an open-source project to help you build websites",
        "Duration": "--",
        "image": "https://source.unsplash.com/1024x768/?nature"
      },
      {
        "id": "2",
        "title": "Inauguration",
        "height": 70,
        "StartDate": "2023-02-26",
        "EndDate": "2023-02-26",
        "StartTime": "11:00 AM",
        "EndTime": "09:00 PM",
        "desc": "Hacker Hive is an open-source project to help you build websites",
        "Duration": "--",
        "image": "https://source.unsplash.com/1024x768/?nature"
      },
      {
        "id": "3",
        "title": "Enspire (Guest Lecture)",
        "height": 70,
        "StartDate": "2023-02-26",
        "EndDate": "2023-02-26",
        "StartTime": "11:00 AM",
        "EndTime": "09:00 PM",
        "desc": "Hacker Hive is an open-source project to help you build websites",
        "image": "https://source.unsplash.com/1024x768/?nature",
        "Duration": "--"
      },
      {
        "id": "4",
        "title": "Hacker Hive Submission Ends",
        "height": 70,
        "StartDate": "2023-02-26",
        "EndDate": "2023-02-26",
        "StartTime": "11:00 AM",
        "EndTime": "09:00 PM",
        "desc": "Hacker Hive is an open-source project to help you build websites",
        "image": "https://source.unsplash.com/1024x768/?nature",
        "Duration": "--"
      },
      {
        "id": "5",
        "title": "Hacker Hive Presentation",
        "height": 70,
        "StartDate": "2023-02-26",
        "EndDate": "2023-02-26",
        "StartTime": "11:00 AM",
        "EndTime": "09:00 PM",
        "desc": "Hacker Hive is an open-source project to help you build websites",
        "image": "https://source.unsplash.com/1024x768/?nature",
        "Duration": "--"
      },
      {
        "id": "6",
        "title": "Lunch Break",
        "height": 70,
        "StartDate": "2023-02-26",
        "EndDate": "2023-02-26",
        "StartTime": "11:00 AM",
        "EndTime": "09:00 PM",
        "desc": "Hacker Hive is an open-source project to help you build websites",
        "image": "https://source.unsplash.com/1024x768/?nature",
        "Duration": "--"
    },
    {
        "id": "7",
        "title": "Arcanum",
        "height": 70,
        "StartDate": "2023-02-26",
        "EndDate": "2023-02-26",
        "StartTime": "11:00 AM",
        "desc": "Hacker Hive is an open-source project to help you build websites",
        "EndTime": "09:00 PM",
        "image": "https://source.unsplash.com/1024x768/?nature",
        "Duration": "--"
    },
    {
        "id": "8",
        "title": "Crack n Swap",
        "height": 70,
        "StartDate": "2023-02-26",
        "EndDate": "2023-02-26",
        "StartTime": "11:00 AM",
        "desc": "Hacker Hive is an open-source project to help you build websites",
        "EndTime": "09:00 PM",
        "image": "https://source.unsplash.com/1024x768/?nature",
        "Duration": "--"
    },
    {
        "id": "9",
        "title": "Just Two Minutes",
        "height": 70,
        "StartDate": "2023-02-26",
        "EndDate": "2023-02-26",
        "StartTime": "11:00 AM",
        "EndTime": "09:00 PM",
        "desc": "Hacker Hive is an open-source project to help you build websites",
        "image": "https://source.unsplash.com/1024x768/?nature",
        "Duration": "--"
    },

      {
        "id": "10",
        "title": "Coding Cauldron",
        "height": 70,
        "StartDate": "2023-02-27",
        "EndDate": "2023-02-27",
        "desc": "Hacker Hive is an open-source project to help you build websites",
        "StartTime": "11:00 AM",
        "EndTime": "09:00 PM",
        "image": "https://source.unsplash.com/1024x768/?nature",
        "Duration": "--"
    },
    {
        "id": "11",
        "title": "Eliminator Round 1",
        "height": 70,
        "StartDate": "2023-02-27",
        "EndDate": "2023-02-27",
        "StartTime": "11:00 AM",
        "image": "https://source.unsplash.com/1024x768/?nature",
        "desc": "Hacker Hive is an open-source project to help you build websites",
        "EndTime": "09:00 PM",
        "Duration": "--"
    },
    {
        "id": "12",
        "title": "Lunch Break",
        "height": 70,
        "StartDate": "2023-02-27",
        "EndDate": "2023-02-27",
        "StartTime": "11:00 AM",
        "EndTime": "09:00 PM",
        "desc": "Hacker Hive is an open-source project to help you build websites",
        "image": "https://source.unsplash.com/1024x768/?nature",
        "Duration": "--"
    },
    {
        "id": "13",
        "title": "Xscape Quest",
        "height": 70,
        "StartDate": "2023-02-27",
        "EndDate": "2023-02-27",
        "StartTime": "11:00 AM",
        "desc": "Hacker Hive is an open-source project to help you build websites",
        "EndTime": "09:00 PM",
        "image": "https://source.unsplash.com/1024x768/?nature",
        "Duration": "--"
    },
    {
        "id": "14",
        "title": "Eliminator Round 2",
        "height": 70,
        "desc": "Hacker Hive is an open-source project to help you build websites",
        "StartDate": "2023-02-27",
        "EndDate": "2023-02-27",
        "StartTime": "11:00 AM",
        "EndTime": "09:00 PM",
        "image": "https://source.unsplash.com/1024x768/?nature",
        "Duration": "--"
    },
    {
        "id": "15",
        "title":"Closing Ceremony",
        "height": 70,
        "StartDate": "2023-02-27",
        "EndDate": "2023-02-27",
        "StartTime": "11:00 AM",
        "EndTime": "09:00 PM",
        "desc": "Hacker Hive is an open-source project to help you build websites",
        "image": "https://source.unsplash.com/1024x768/?nature",
        "Duration": "--"
    }
];